language: rust

env:
  global:
    - secure: VKiZFaVm2s94iC2ogZ7b/bXFOh2QprdyqVq9l1zuUjXxFnzaVHwDwvcu8bO7Z6GFlu3X39efxP04CtzaapNNIUoqKGl5v/j850ILsUBl7BhjVXMLbpWjySn0uSxxln0pnB0vtiQSksqrV6hG3vCqrc/8Rsi2RzQwjMf8W+0Y7p8=

install:
  - sudo apt-get install libXxf86vm-dev libosmesa6-dev

after_script:
  - cargo doc
  - cp -R target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
