sudo: false

language: rust

rust:
    - nightly
    - stable

matrix:
  allow_failures:
    - rust: nightly

env: 
  global:
    - secure: "Ts/4pe5X+GCq2tr88UyXvIciibED0vHaJhQE9gC4OIyJRIM4ZBiNmyVATZi16zWzLPVCkURWBIjMt5G7r7rJ0fwvGvsFUfCMg9if1xYEVgXBw/0FFvgO5CkUR+vK3lD1A9Gew1exCwz/bKz0Vf2NvHcpBdvZ3pUbageLRGKcVH4="
    - secure: "AfE+PLANOT0mgUKpgGUu4yIrSNKxoNST5zFBeajONEEE0wl/bZVE6iGqucNPR0EaIgMfk+NGgCLLM7VFfy+HF5alBiqUUOapef+fc91iHVzoBgtlLXOO7E1UntrieBQCodURTaBtotCMe7jtlkNajkvUD6atKTYh1AYJ3JY2bHA="
    - GLIUM_HEADLESS_TESTS=1
  matrix:
    - FEATURES='' TEST=0 COVERAGE=0
    - FEATURES='headless glutin' TEST=1 COVERAGE=0
    - FEATURES='headless glutin image cgmath nalgebra gl_read_buffer gl_depth_textures' TEST=1 COVERAGE=1
    - FEATURES='headless glutin image cgmath nalgebra gl_read_buffer gl_depth_textures gl_read_buffer gl_uniform_blocks gl_sync gl_program_binary gl_tessellation gl_instancing gl_integral_textures gl_depth_textures gl_stencil_textures gl_bindless_textures' TEST=0 COVERAGE=0

addons:
  apt:
    packages:
    - libxxf86vm-dev
    - libosmesa6-dev
    - libcurl4-openssl-dev      # for kcov
    - libelf-dev                # for kcov
    - libdw-dev                 # for kcov
    - cmake                     # for kcov

script:
    # We run everything with `-j 1` or travis runs out of memory
    - cargo build -v --no-default-features --features "$FEATURES"
    - if [ "$TEST" -eq 1 ]; then cargo test -v -j 1 --no-default-features --features "$FEATURES"; fi
    #- if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then cargo test -v --manifest-path macros/Cargo.toml; fi

after_success: 
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        [ $TRAVIS_RUST_VERSION = nightly ] &&
        cargo doc -j 1 --features "headless gl_read_buffer gl_uniform_blocks gl_sync gl_program_binary gl_tessellation gl_instancing gl_integral_textures gl_depth_textures gl_stencil_textures gl_texture_1d gl_texture_3d gl_texture_multisample gl_texture_multisample_array gl_bindless_textures" &&
        cp -R doc/* target/doc &&
        git clone https://github.com/davisp/ghp-import &&
        ./ghp-import/ghp-import target/doc &&
        git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        cargo publish --no-verify --token ${CRATESIO_TOKEN}
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        cargo publish --no-verify --token ${CRATESIO_TOKEN} --manifest-path macros/Cargo.toml
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        [ "$COVERAGE" -eq 1 ] &&
        wget https://github.com/SimonKagstrom/kcov/archive/master.zip &&
        unzip master.zip && mv kcov-master kcov && mkdir kcov/build && cd kcov/build &&
        cmake .. && make && make install DESTDIR=../built && cd ../.. &&
        for file in ./target/debug/*; do ./kcov/built/usr/local/bin/kcov --exclude-pattern=/.cargo ./target/kcov ${file}; done &&
        ./kcov/built/usr/local/bin/kcov --coveralls-id=${TRAVIS_JOB_ID} --merge ./target/kcov-merge ./target/kcov
