language: rust

env: HEADLESS_TESTS=1

install:
  - sudo apt-get install libXxf86vm-dev libosmesa6-dev

script:
    - cargo build --verbose
    - cargo test --verbose
    - cargo test --no-default-features --verbose

after_script:
  - cargo bench
